---
language: cpp
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - g++-4.8-multilib
    - gcc-multilib
    - libxtst-dev
    - libpng++-dev

# Build matrix
os:
- linux
- osx
env:
  global:
    secure: <env>
  matrix:
#  - TRAVIS_NODE_VERSION="6" ARCH="x86"
  - TRAVIS_NODE_VERSION="12" ARCH="x64"
#  - BINARY_BUILDER="true" TRAVIS_NODE_VERSION="8" ARCH="x86"
# disable x86 for now because of weird errors with gyp under prebuild

matrix:
  exclude:
  - os: osx
    env: TRAVIS_NODE_VERSION="12" ARCH="x86"

before_install:

# download node if testing x86 architecture
- >
  if [[ "$ARCH" == "x86" ]]; then
    BASE_URL=$(node -p "'https://nodejs.org/dist/' + process.version");
    X86_FILE=$(node -p "'node-' + process.version + '-' + process.platform + '-x86'");
    wget $BASE_URL/$X86_FILE.tar.gz;
    tar -xf $X86_FILE.tar.gz;
    nvm deactivate;
    export PATH=$X86_FILE/bin:$PATH;
  else
    nvm install $TRAVIS_NODE_VERSION
  fi;

# use g++-4.8 on Linux
- if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-4.8; fi
- $CXX --version

# print versions
- echo "--------------------------"
- uname -a
- which node; file `which node`
- node --version
- node -p 'process.platform + "@" + process.arch'
- npm --version

# figure out if we should publish
- PUBLISH_BINARY=false
- echo $TRAVIS_BRANCH
- echo `git describe --tags --always HEAD`
- if [[ $TRAVIS_BRANCH == `git describe --tags --always HEAD` ]]; then PUBLISH_BINARY=true; fi;
- echo "Publishing native platform Binary Package? ->" $PUBLISH_BINARY

install:
- npm install

script:
# if publishing, do it
- >
  if [[ $PUBLISH_BINARY == true ]]; then
    ./node_modules/.bin/prebuild --all -u $prebuild_upload;
  fi;
